name: Rust

on:
  workflow_dispatch:
    inputs:
      repo:
        description: Repository
        required: true
      ref:
        description: Branch or Tag
        required: false
        default: "main"
      name:
        description: Project Name
        required: true
      toolchain:
        description: Rust Version
        required: false
        default: "stable"
      args:
        description: Build Options
        required: false
        default: "--locked --release"
      prep:
        description: Pre-Build Steps
        required: false
        default: 'echo "nothing to do"'
      preptargets:
        description: Targets for Pre-Build Steps
        required: false
      target:
        description: Custom Target
        required: false
      os:
        description: Custom OS
        required: false
      extra_artifacts:
        description: Extra Artifacts to Include
        required: false
        default: "README.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    outputs:
      commit: ${{ steps.commit.outputs.hash }}

    strategy:
      fail-fast: false
      matrix:
        os: ["${{ inputs.os || 'ubuntu-22.04' }}"]
        target: ["${{ inputs.target || 'x86_64-unknown-linux-gnu' }}"]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest

          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest

          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repo }}
          submodules: recursive
          fetch-depth: 2

      - name: Setup Cargo Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ inputs.name }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Install ouch
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: ouch

      - name: Get commit hash # For release notes
        id: commit
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Rust (${{ inputs.toolchain }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}
          target: ${{ matrix.target }}
          override: true
          default: true

      - name: Pre-Build Steps
        id: prep
        if: contains(inputs.preptargets, matrix.target)
        run: ${{ inputs.prep }}

      - name: Build ${{ inputs.name }}
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ !contains(matrix.target, 'x86_64') }}
          command: build
          args: --target ${{ matrix.target }} ${{ inputs.args }}

      - name: Create Release Bundle
        run: ouch compress --slow target/${{ matrix.target }}/release ${{ inputs.extra_artifacts }} ${{ inputs.name }}-${{ matrix.target }}.tar.gz

      - name: Upload Builds
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          include-hidden-files: true
          compression-level: 0
          name: build-${{ matrix.target }}
          path: ${{ inputs.name }}-${{ matrix.target }}.tar.gz

  release:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      packages: write
      actions: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: release
          pattern: "build-*"
          separate-directories: false
          delete-merged: false
          retention-days: 1

      - name: Download Builds
        uses: actions/download-artifact@v4
        with:
          name: release
          path: release
          merge-multiple: true

      - name: Prep Release Notes
        working-directory: release
        run: |
          echo 'source: ${{ inputs.repo }}@${{ needs.build.outputs.commit }}' | tee ../notes.md
          echo -e '\n```sh\necho $hash $filename | sha1sum -c\n' | tee -a ../notes.md
          sha1sum $(ls) | tee -a ../notes.md
          echo '```' | tee -a ../notes.md

      - name: Generate Provenance Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'release/*'

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.repo }}/${{ needs.build.outputs.commit }}
          name: ${{ inputs.name }}@${{ inputs.ref }}
          makeLatest: true
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "release/*"
          bodyFile: "notes.md"
          token: ${{ github.token }}
